### ISSUE TITLE
Issue with launching

### ISSUE THREAD

**Issue by KienVu1** [Aetopia/Lunar-Client-Lite-Launcher#10]
When I launch lcl windows just closes and nothing happens.
I use -Xms1G -Xmx1G -Xmn768m -XX:+DisableAttachMechanism jvm Arguments
and lastest version of lcl

**Comment by Aetopia** [comment]
Make sure, you clear out the old arguments out of JVM arguments or else LCL will attempt to launch `javaw.exe` but due to invaild arguments nothing will launch.

**Comment by KienVu1** [comment]
i launch lcl with no Arguments. it's launching but only 256mb ram allocated ;/
if u use others jvm Arguments game wont launch ://

**Comment by Aetopia** [comment]
make sure, you don't have any other java installations on your system.

**Comment by KienVu1** [comment]
i deleted zulu jre/jdk 
and nothing happen when i launch :/ 
i use -Xms1G -Xmx1G -Xmn768m -XX:+DisableAttachMechanism  jvm agr

**Comment by Aetopia** [comment]
I have you tried using other arguments?
