### ISSUE TITLE
Store all files that LCL generates in user app data

### ISSUE THREAD

**Issue by he3als** [Aetopia/Lunar-Client-Lite-Launcher#12]
This makes it so if LCL is in Program Files it can save settings without being run as admin (due to permissions).

**Comment by Aetopia** [comment]
Why do you want LCL in Program Files in the first place?

**Comment by he3als** [comment]
i store programs in there

**Comment by Aetopia** [comment]
LCL is meant to be portable also. Not considering to change the config directory.

**Comment by As54d** [comment]
m
