### ISSUE TITLE
Make a slider for RAM allocation

### ISSUE THREAD

**Issue by he3als** [Aetopia/Lunar-Client-Lite-Launcher#13]
Like in the original launcher, add a slider for RAM allocation. For advanced users, also add an option to not use the RAM slider and instead depend on the JVM arguments.

**Comment by Aetopia** [comment]
Yeh, that could be a useful feature, meaning that JVM Arguments will be like MultiMC.

**Comment by Aetopia** [comment]
But I don't what to keep the maximum memory allocation for LCL.

**Comment by he3als** [comment]
i would just put the max memory allocation to 4.5 as i think that should be the maximum you would need

**Comment by Aetopia** [comment]
maybe have some optimized arguments hardcoded into the launcher and a toggle to enable manual arguments.

**Comment by he3als** [comment]
yeah sure if them args are really the best and if they are tested
