### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by PKSMc** [Aetopia/Lunar-Client-Lite-Launcher#14]
Hey I want this to be on linux too cause I can get even more fps boost I tried to use wine program but when I click it said no lunar client detect so I tried to download .exe on linux and install it using wine and it stuck at extracting package.7z :/ pls add it for ubuntu!

**Comment by PKSMc** [comment]
on linux the lunar client has no debian package (.deb) so I can't install it it's appimage when I click it it just appear the launcher

**Comment by Aetopia** [comment]
LCL is written in AHK so it won't have support for Linux.

**Comment by couleurm** [comment]
[This](https://github.com/couleur-tweak-tips/utils/raw/main/LCLI.bat) is what LCL is based on, feel free to rewrite it in bash

**Comment by he3als** [comment]
Using Wine will not be a good solution for this as well. You can use the launch command manually if you would like. Otherwise, LCL will probably never have support for any other operating systems except from Windows, unless it gets rewritten.

**Comment by Aetopia** [comment]
I am thinking of making in bash, but via a VM.

**Comment by Aetopia** [comment]
https://github.com/Aetopia/LCL-Linux

**Comment by couleurm** [comment]
python :content:

**Comment by Aetopia** [comment]
> 
> 
> python :content:

mhm
