### ISSUE TITLE
Questions about my use of LCL

### ISSUE THREAD

**Issue by As54d** [Aetopia/Lunar-Client-Lite-Launcher#16]
Why is there a sound when I use Lunar client to play games,
There is no sound when playing games with LCL,
How is this going?

**Comment by Aetopia** [comment]
Try to run LCL as an admin if there is no sound.
The same fix will work also for the official Lunar Client launcher also.

**Comment by Aetopia** [comment]
No Response, closing this issue.

**Comment by As54d** [comment]
> 如果没有声音，请尝试以管理员身份运行 LCL。 同样的修复也适用于官方 Lunar Client 启动器。

Already tried it still doesn't work, no sound effects

**Comment by As54d** [comment]
This is really a big problem. There is no sound effect when playing games.

**Comment by As54d** [comment]
How to fix this

**Comment by As54d** [comment]
> 无响应，关闭此问题。
Sorry i went to school

**Comment by Aetopia** [comment]
Have you tried to use the latest Patch?
