### ISSUE TITLE
Add Chinese LangFile

### ISSUE THREAD

**Issue by Cang-Yue** [Aetopia/Lunar-Client-Lite-Launcher#18]
Hello I translate your program to Chinese(zh_cn)
Can you add it in next update?
Thankyou
[chinese.txt](https://github.com/Aetopia/Lunar-Client-Lite-Launcher/files/7271383/chinese.txt)
[chineseui.txt](https://github.com/Aetopia/Lunar-Client-Lite-Launcher/files/7271384/chineseui.txt)

**Comment by Aetopia** [comment]
Added with `v1.6.4`.
