### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by samhorizon7** [Aetopia/Lunar-Client-Lite-Launcher#19]
it says "You must have the launcher open."

**Comment by Aetopia** [comment]
Launch the LC Launcher and keep it in the background while signing in.

**Comment by samhorizon7** [comment]
I dont get it. Do I open the regular lunar client then sign in?

**Comment by samhorizon7** [comment]
nvm fixed it

**Comment by Aetopia** [comment]
Fixed.
