### ISSUE TITLE
Assigning a directory to a specific version

### ISSUE THREAD

**Issue by conc1erge** [Aetopia/Lunar-Client-Lite-Launcher#2]
Not really an issue, more of a suggestion:

Really hate how I gotta change my directory from the main .minecraft directory if I wanna switch from the latest versions to 1.7.10.
For example:
1.7.10 would use: `C:\Users\<user>\AppData\Roaming\.minecraft\1.7.10` 
and 1.16/1.17 would use: `C:\Users\<user>\AppData\Roaming\.minecraft` 

Overall, I love the concept of this!

**Comment by Aetopia** [comment]
Its entirely possible, just a few lines of code and some changes to the wrapper script, can make it possible it implement this.
Its not a priority to add this rn so I might add this sometime later.

**Comment by Aetopia** [comment]
This will be likely added in a future update.

**Comment by Aetopia** [comment]
I won't be making this feature part of the main branch but rather an experimental update. LC Lite doesn't download minecraft dependenices, so issues like "no sound coming" can since there's no asset index in the directory.

**Comment by conc1erge** [comment]
Officially supported as of August 13, 2021, closing issue.
