### ISSUE TITLE
No sound when using LCL

### ISSUE THREAD

**Issue by majdf** [Aetopia/Lunar-Client-Lite-Launcher#30]
When launching with default lunar client launcher, everything works fine. When launching with LCL, there is no sound. Windows doesn't detect any sound coming from the client,  and I have checked all my settings to make sure that it should be working fine.

**Comment by Aetopia** [comment]
![image](https://user-images.githubusercontent.com/41850963/142359077-3763be0e-8950-42f6-b383-9e5e2430b679.png)
