### ISSUE TITLE
Suggestion: Add an option to use a custom javaw executable

### ISSUE THREAD

**Issue by he3als** [Aetopia/Lunar-Client-Lite-Launcher#4]
# Suggestion
Add an option to use a custom javaw executable.

# Purpose
The purpose is to be able to use something like GraalVM for possibly better performance.

**Comment by Aetopia** [comment]
This is entirely possible but then you have issues with compatibility. You will need to test the custom jre which I implement in a fork of the repo.

**Comment by Aetopia** [comment]
Lunar uses Zulu JRE 16 to have support for MS accounts and MC `1.17`.

**Comment by he3als** [comment]
I have tested GraalVM 16 with Lunar Client and it works fine, the only issue is that you can not sign in with Microsoft without crashing (if you are already signed in, everything works).

**Comment by Aetopia** [comment]
It works! If possible, could you some optimized JVM Args for GradleVM 16?

**Comment by Aetopia** [comment]
![image](https://user-images.githubusercontent.com/41850963/131252011-125b0bc4-8a29-43a7-9088-69125300235e.png)
Preview of the GUI.

**Comment by he3als** [comment]
niceee

**Comment by Aetopia** [comment]
zulu 16.32.xxx just crashes lunar client.

**Comment by Aetopia** [comment]
https://github.com/Aetopia/Lunar-Client-Lite-Launcher/releases/tag/v1.4-adv.1
I made a new release with Custom Java Executable Support.
Here is the LCL advanced repository: https://github.com/Aetopia/Lunar-Client-Lite-Launcher/tree/Advanced

**Comment by he3als** [comment]
nice

**Comment by Aetopia** [comment]
Should I close this or want anything else?

**Comment by he3als** [comment]
yeah i will close it
