### ISSUE TITLE
Error: could not create the java virtual machine

### ISSUE THREAD

**Issue by antintin0** [Aetopia/Lunar-Client-Lite-Launcher#8]
I get the following error when trying to launch with any java version other than the zulu 16 version that lunar uses by default:
![image](https://user-images.githubusercontent.com/67392684/131941638-b39c79c9-be19-4564-958f-076e4f6871be.png)

 This same error occurs both with installed java versions and extracted zip ones. I've tried IBM Openj9, oracle jre 8, and zulu jre 8

**Comment by antintin0** [comment]
Well I guess lunar only accepts java 16. Just tried it with the IBM one but java 16 and it worked. Unfortunate

**Comment by Aetopia** [comment]
> 
> 
> Well I guess lunar only accepts java 16. Just tried it with the IBM one but java 16 and it worked. Unfortunate

I think Lunar clearly stated they will switching to java 16 to support ms accounts.

**Comment by Aetopia** [comment]
> 
> 
> Well I guess lunar only accepts java 16. Just tried it with the IBM one but java 16 and it worked. Unfortunate

wdym by ibm one?

**Comment by Aetopia** [comment]
Anything else or should I close this?
